# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\atsu\Desktop\W5200_PSoC4_test\W5200_PSoC4_test.cydsn\W5200_PSoC4_test.cyprj
# Date: Wed, 30 Oct 2013 05:06:24 GMT
#set_units -time ns
create_clock -name {UART_1_SCBCLK(FFB)} -period 8687.5 -waveform {0 4343.75} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {SPI_SCBCLK(FFB)} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_generated_clock -name {UART_1_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 417 835} [list]
create_generated_clock -name {SPI_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 5} [list]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for C:\Users\atsu\Desktop\W5200_PSoC4_test\W5200_PSoC4_test.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\atsu\Desktop\W5200_PSoC4_test\W5200_PSoC4_test.cydsn\W5200_PSoC4_test.cyprj
# Date: Wed, 30 Oct 2013 05:06:21 GMT
