/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <UART_1.h>
#include <UART_1_SPI_UART.h>
#include <UART_1_PINS.h>
#include <UART_1_SPI_UART_PVT.h>
#include <UART_1_PVT.h>
#include <SPI.h>
#include <SPI_SPI_UART.h>
#include <SPI_PINS.h>
#include <SPI_SPI_UART_PVT.h>
#include <SPI_PVT.h>
#include <SPI_CS.h>
#include <SPI_CS_aliases.h>
#include <UART_1_rx.h>
#include <UART_1_rx_aliases.h>
#include <UART_1_SCBCLK.h>
#include <UART_1_tx.h>
#include <UART_1_tx_aliases.h>
#include <SPI_ss0_m.h>
#include <SPI_ss0_m_aliases.h>
#include <SPI_mosi_m.h>
#include <SPI_mosi_m_aliases.h>
#include <SPI_miso_m.h>
#include <SPI_miso_m_aliases.h>
#include <SPI_sclk_m.h>
#include <SPI_sclk_m_aliases.h>
#include <SPI_SCBCLK.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

